
import java.awt.Color;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brayan
 */
public class ForgetPass extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPass
     */
    public ForgetPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_contenedor = new javax.swing.JPanel();
        Label_icon = new javax.swing.JLabel();
        Panel_topPass = new javax.swing.JPanel();
        Btn_close = new javax.swing.JPanel();
        label_Xclose = new javax.swing.JLabel();
        Label_forgetpass = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jSeparator_user = new javax.swing.JSeparator();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jSeparator_email = new javax.swing.JSeparator();
        jLabel_newPass = new javax.swing.JLabel();
        jTextField_newPass = new javax.swing.JTextField();
        jSeparator_newPass = new javax.swing.JSeparator();
        jLabel_ConfirmPass = new javax.swing.JLabel();
        jTextField_ConfirmPass = new javax.swing.JTextField();
        jSeparator_ConfirmPass = new javax.swing.JSeparator();
        Btn_Confir = new javax.swing.JPanel();
        label_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Favicon login.png"))); // NOI18N
        Panel_contenedor.add(Label_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 52, 29));

        Panel_topPass.setBackground(new java.awt.Color(255, 255, 255));

        Btn_close.setBackground(new java.awt.Color(255, 255, 255));

        label_Xclose.setBackground(new java.awt.Color(255, 255, 255));
        label_Xclose.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        label_Xclose.setForeground(new java.awt.Color(0, 0, 0));
        label_Xclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Xclose.setText("X");
        label_Xclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Xclose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Xclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_XcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_XcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_XcloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Btn_closeLayout = new javax.swing.GroupLayout(Btn_close);
        Btn_close.setLayout(Btn_closeLayout);
        Btn_closeLayout.setHorizontalGroup(
            Btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Xclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        Btn_closeLayout.setVerticalGroup(
            Btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Xclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_topPassLayout = new javax.swing.GroupLayout(Panel_topPass);
        Panel_topPass.setLayout(Panel_topPassLayout);
        Panel_topPassLayout.setHorizontalGroup(
            Panel_topPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_topPassLayout.createSequentialGroup()
                .addGap(0, 482, Short.MAX_VALUE)
                .addComponent(Btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_topPassLayout.setVerticalGroup(
            Panel_topPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_topPassLayout.createSequentialGroup()
                .addComponent(Btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel_contenedor.add(Panel_topPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        Label_forgetpass.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Label_forgetpass.setForeground(new java.awt.Color(0, 0, 0));
        Label_forgetpass.setText("Recuperacion de contraseña");
        Panel_contenedor.add(Label_forgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        label_user.setForeground(new java.awt.Color(0, 0, 0));
        label_user.setText("Nombre de usuario");
        Panel_contenedor.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 151, -1));

        jTextField_user.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_user.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_user.setBorder(null);
        Panel_contenedor.add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 235, -1));
        Panel_contenedor.add(jSeparator_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 235, 10));

        jLabel_email.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_email.setText("Correo electronico:");
        Panel_contenedor.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 151, -1));

        jTextField_email.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_email.setBorder(null);
        Panel_contenedor.add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 235, -1));
        Panel_contenedor.add(jSeparator_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 235, 10));

        jLabel_newPass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_newPass.setText("Contraseña nueva:");
        Panel_contenedor.add(jLabel_newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 151, -1));

        jTextField_newPass.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_newPass.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_newPass.setBorder(null);
        Panel_contenedor.add(jTextField_newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 235, -1));
        Panel_contenedor.add(jSeparator_newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 235, 10));

        jLabel_ConfirmPass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_ConfirmPass.setText("Confirmar contraseña");
        Panel_contenedor.add(jLabel_ConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 151, -1));

        jTextField_ConfirmPass.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_ConfirmPass.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_ConfirmPass.setBorder(null);
        Panel_contenedor.add(jTextField_ConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 235, -1));
        Panel_contenedor.add(jSeparator_ConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 235, 10));

        Btn_Confir.setBackground(new java.awt.Color(255, 231, 179));
        Btn_Confir.setForeground(new java.awt.Color(0, 0, 0));

        label_btn.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        label_btn.setForeground(new java.awt.Color(0, 0, 0));
        label_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_btn.setText("Confirmar");
        label_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Btn_ConfirLayout = new javax.swing.GroupLayout(Btn_Confir);
        Btn_Confir.setLayout(Btn_ConfirLayout);
        Btn_ConfirLayout.setHorizontalGroup(
            Btn_ConfirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Btn_ConfirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Btn_ConfirLayout.setVerticalGroup(
            Btn_ConfirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Btn_ConfirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_contenedor.add(Btn_Confir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        getContentPane().add(Panel_contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_XcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_XcloseMouseClicked

        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_label_XcloseMouseClicked

    private void label_XcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_XcloseMouseEntered
        Btn_close.setBackground(Color.red);
        label_Xclose.setForeground(Color.white);
    }//GEN-LAST:event_label_XcloseMouseEntered

    private void label_XcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_XcloseMouseExited
         Btn_close.setBackground(Color.white);
        label_Xclose.setForeground(Color.black);
    }//GEN-LAST:event_label_XcloseMouseExited

    private void label_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_btnMouseClicked
         javax.swing.JOptionPane.showMessageDialog(this, "Cambio de contraseña exitoso", "Cambio de contraseña", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_label_btnMouseClicked

    private void label_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_btnMouseEntered
          Btn_Confir.setBackground(new Color(255,236,196));
    }//GEN-LAST:event_label_btnMouseEntered

    private void label_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_btnMouseExited
        Btn_Confir.setBackground(new Color(255,231,179));
    }//GEN-LAST:event_label_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Btn_Confir;
    private javax.swing.JPanel Btn_close;
    private javax.swing.JLabel Label_forgetpass;
    private javax.swing.JLabel Label_icon;
    private javax.swing.JPanel Panel_contenedor;
    private javax.swing.JPanel Panel_topPass;
    private javax.swing.JLabel jLabel_ConfirmPass;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_newPass;
    private javax.swing.JSeparator jSeparator_ConfirmPass;
    private javax.swing.JSeparator jSeparator_email;
    private javax.swing.JSeparator jSeparator_newPass;
    private javax.swing.JSeparator jSeparator_user;
    private javax.swing.JTextField jTextField_ConfirmPass;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_newPass;
    private javax.swing.JTextField jTextField_user;
    private javax.swing.JLabel label_Xclose;
    private javax.swing.JLabel label_btn;
    private javax.swing.JLabel label_user;
    // End of variables declaration//GEN-END:variables
}
